export const meetingSummaryConcise = [
  "The speaker provides an overview of their Fireflies AI clone project, detailing the recreation of the user experience, interface design, and meeting management workflow. They explain the functionalities of the landing page, sign-up/sign-in process, dashboard, and various features like daily brief, meeting status, and transcript uploads, while also noting current limitations and future development plans.",
  "",
  "1. Project Overview and Initial User Experience:",
  "• Project Goal: The primary goal was to recreate the overall Fireflies user experience, interface design, and meeting management workflow as closely as possible.",
  "• Landing Page: The landing page greets users with 'the has one AI assistant for your meeting'. Two options are presented: 'getting started' and 'request demo'.",
  "• Sign-up/Sign-in Process: Users can type any email to sign up or log in. There is no record function implemented at this time.",
  "• Dashboard: Most of the dashboard is similar to the original Fireflies.AI, with minor UI design differences.",
  "",
  "2. Dashboard Features and Functionality:",
  "• Homepage Greeting: The homepage greets users with 'good morning' or 'good afternoon'.",
  "• Main Options: 'daily brief', 'meeting', 'perhaps', 'task schedule', 'meetings upload file', and 'capture meeting'.",
  "• Meeting Status: A 'firefly test' meeting status is visible on the screen. Inside, notes summarize the meeting, including a timestamp and the main point.",
  "• Transcript Options: On the left side of the screen, 'askfred' or 'transcript' options are available. The transcript option displays the entire spoken content of the meeting.",
  "• Upload Functionality: Users can upload MP4 files to generate a transcript.",
  "",
  "3. Future Development and Limitations:",
  "• Non-functional Features: 'Meeting, perhaps' and 'capture meeting' are not functional for direct transcript generation or connection to Zoom meetings.",
  "• AI Integration: AI is not currently attached for direct transcript generation from meetings.",
  "• Future Upgrades: The speaker would like to add upload options in the future. AI integration is considered the last thing to add, as it would be a plugin."
];

export const meetingSummaryDetailed = [
  "Interview recording 2",
  "The speaker provides an overview of their Fireflies AI clone project, detailing the recreation of the user experience, interface design, and meeting management workflow. They explain the functionalities of the landing page, signup/signin process, dashboard, and various features like daily brief, meeting status, and transcript uploads, while also noting current limitations and future development plans.",
  "",
  "1. Project Overview and Initial User Experience:",
  "• Project Goal: The primary goal was to recreate the overall Fireflies user experience, interface design, and meeting management workflow as closely as possible.",
  "• Landing Page:",
  "  Greeting: The landing page greets users with \"the has one AI assistant for your meeting\".",
  "  Options: Two options are presented: \"getting started\" and \"request demo\".",
  "  Functionality: The \"request demo\" option does not show anything, while \"get started\" leads to the signup page.",
  "• Signup/Signin Process:",
  "  Email Input: Users can type any email, even \"AB at the red gmail dot com\", to sign up or log in.",
  "  Record Function: There is no record function implemented at this time.",
  "• Dashboard:",
  "  Similarity: Most of the dashboard is similar to the original Fireflies.AI.",
  "  UI Differences: Minor UI design differences exist, such as the absence of a gradient flow seen on the original homepage.",
  "",
  "2. Dashboard Features and Functionality:",
  "• Homepage Greeting: The homepage greets users with \"good morning\" or \"good afternoon\".",
  "• Main Options: The main options available are \"daily brief\", \"meeting\", \"perhaps\", \"task schedule\", \"meetings upload file\", and \"capture meeting\".",
  "• Daily Brief:",
  "  Function: Users can access a daily brief of their productivity.",
  "• Meeting Status:",
  "  Current Status: A \"firefly test\" meeting status is visible on the screen.",
  "  Meeting Summary: Inside the meeting status, a box or notes summarize the meeting, including a timestamp and the main point at that timestamp.",
  "• Transcript Options:",
  "  Askfred/Transcript: On the left side of the screen, \"askfred\" or \"transcript\" options are available.",
  "  Transcript Content: The transcript option displays the entire spoken content of the meeting.",
  "  Audio Playback: A play icon for audio is located at the bottom of the screen, but it is not currently working.",
  "• Upload Functionality:",
  "  Purpose: Users can upload MP4 files to generate a transcript.",
  "  Current Status: This feature is currently a placeholder and not fully attached.",
  "",
  "3. Future Development and Limitations:",
  "• Nonfunctional Features: \"Meeting, perhaps\" and \"capture meeting\" are not functional for direct transcript generation or connection to Zoom meetings.",
  "• AI Integration: AI is not currently attached for direct transcript generation from meetings.",
  "• Future Upgrades:",
  "  Upload Options: The speaker would like to add upload options in the future.",
  "  AI Integration: AI integration is considered the last thing to add, as it would be a plugin.",
  "• Current Focus: The current focus is on the \"UNUS part\" of the project."
];

export const meetingTranscript = [
  { speaker: "Speaker 1", time: "00:05", text: "Hello and welcome to my fireflies AI clone project. For this assignment. My prime primary goal was to recreate the overall firefly's user experience, interface design, and meeting management workflow as closely as possible.", seconds: 5 },
  { speaker: "Speaker 1", time: "00:22", text: "So going forward, I will be telling you little bit about my assignment that I have done and a little tour about this whole web page. Or you can save web APP. So going forward, the first page you will be greeted with,", seconds: 22 },
  { speaker: "Speaker 1", time: "00:39", text: "when you ah come to this website, it will be a landing page where youWill see a little icon of fireflies AI because it is a clone application. I didn't change the main theme of ah fireflies AI,", seconds: 39 },
  { speaker: "Speaker 1", time: "00:55", text: "ah because I think the main name of was ah main name of assignment was to recreate existing ah platform, ah to know the capability of candidate.", seconds: 55 },
  { speaker: "Speaker 1", time: "01:06", text: "So I didn't go in deep about recreating the UI part because the designing part also takes some of the time and I don't want to ruin the mean firefly ah firefly files kind of system. So the first ah,", seconds: 66 },
  { speaker: "Speaker 1", time: "01:21", text: "page will be a get a started page or ALanding page. Where will you be greeted with a the has one AI assistant for your meeting? There will be two options in front of you. One will be getting started.", seconds: 81 },
  { speaker: "Speaker 1", time: "01:37", text: "Second will be request demo, I don't think and request request demo will show you anything because I didn't design this. But if you go on get started, you'll be going on sign up page. But it doesn't matter.", seconds: 97 },
  { speaker: "Speaker 1", time: "01:53", text: "Even if you go and sign up or sign in page, both ah will just, you have to type any email. it doesn't have to be a legal one. I will say, ahLet me try once because I don't think I have put it that way. But yeah,", seconds: 113 },
  { speaker: "Speaker 1", time: "02:10", text: "you can like ah type an email and it will login even AB at the red gmail dot com. When you sign up, all login, both are same thing. There will be no record because I didn't degrade the record function right now.", seconds: 130 },
  { speaker: "Speaker 1", time: "02:27", text: "So you will we get to the dashboard of fireflies dot AI. Most of the dashboard will be same as the original firefly dot a. There will be difference in UI designs, not the major different. There will be like,", seconds: 147 },
  { speaker: "Speaker 1", time: "02:43", text: "if you go onOriginal homepage of firefly, you'll see a gradient, a little flow going on there. I didn't add that thing right now. Ah so it's lacking. Ah maybe if I have time, ah so I will add it.", seconds: 163 },
  { speaker: "Speaker 1", time: "02:58", text: "But right now I am going to record this audio. So if you come on the homepage, homepage will be a greeting for you. Like good morning and good afternoon. And the greeting page,", seconds: 178 },
  { speaker: "Speaker 1", time: "03:12", text: "and the more most of the option will be daily brief meeting, perhaps task schedule, meetings upload file, capture meeting, same as the originalFireflies one. If you go in daily brief,", seconds: 192 },
  { speaker: "Speaker 1", time: "03:26", text: "you'll be on the second page where you can get a daily brief of your productivity and things around. You can play around with these things and understand how the workflow works. Ah going into the main part of things,", seconds: 206 },
  { speaker: "Speaker 1", time: "03:43", text: "ah like meeting, perhaps, or capture meeting. Ah right now, it's not functional. Ah to directly get the transcript or get connected to your zoom meeting and get your transcript because AI is not attached.", seconds: 223 },
  { speaker: "Speaker 1", time: "03:59", text: "But for sampling purpose I am recording thisAudio. After recording this audio, there will be created a task for it that you can see in the meeting status. Ah but ah if you go right now, right now,", seconds: 239 },
  { speaker: "Speaker 1", time: "04:15", text: "I already created one meeting status where I was suggesting in this dashboard earlier. So it's a firefly test right now visible on my screen. And if I go inside it,", seconds: 255 },
  { speaker: "Speaker 1", time: "04:28", text: "it will be AA little box there or I will say little notes there where it will summarize the whole meeting that's gone and like it's recorded and the transcript was created and then itSummarized it,", seconds: 268 },
  { speaker: "Speaker 1", time: "04:43", text: "but it will be a timestamp there. And at that timestamp ah timestamp. What was the main point of that? Ah timestamp? And there will be two, three timestamp. Um as according to the AI that transcript theWhole.", seconds: 283 },
  { speaker: "Speaker 1", time: "05:00", text: "After that, if you see in the left side of the screen, you will find a askfred or transcript option. In transcript, there will be whole transcript of things there. Like what? Ah the whole things was spoken there.", seconds: 300 },
  { speaker: "Speaker 1", time: "05:17", text: "And in the downside of the whole screen, you will find a play by icon of audio. Right now. it's not working because I am recording it right now. But after integrating this voice in this,", seconds: 317 },
  { speaker: "Speaker 1", time: "05:32", text: "I will make sure to the audio run and the transcript that I attach with it, then with it right now, it's notWorking, but you will see it's working when you are ah listening to this audio. If you go on the next option,", seconds: 332 },
  { speaker: "Speaker 1", time: "05:49", text: "it will be upload of our transcript a basically not transcript. Ah, ah here you can upload AMP four like right now I am recording and it will generate a transcript for you and give you ah the,", seconds: 349 },
  { speaker: "Speaker 1", time: "06:04", text: "it's also a placeholder right now because I don't attached it. But yeah, most of the feature that was the original website, I tried to recreate most of them, but some are not that much up to the mark, IWill say, but in future,", seconds: 364 },
  { speaker: "Speaker 1", time: "06:22", text: "if I have to recreate this whole thing or I will say upgrade this whole thing, I really like to add ah upload options and AI integration.", seconds: 382 },
  { speaker: "Speaker 1", time: "06:33", text: "I will choose AI integration in the last because AI integration will be the last thing or a plugin for this. The ah I know the main ah file file ah flies. The main aim is to create the transcript.", seconds: 393 },
  { speaker: "Speaker 1", time: "06:48", text: "But right now I am focusing on UNUS part. So most of the things are done and this will be the end of my audio play. Thank you for listening to me.And a little bit boring. But okay, if someone is listening, I will be happy.", seconds: 408 },
  { speaker: "Speaker 1", time: "07:06", text: "Also here on out, I'm signing off. ThankYou.", seconds: 426 }
];
